version: "3.9"

services:
  postgres_valuation:
    image: postgres:15
    container_name: asset_valuation_db_pg
    environment:
      POSTGRES_DB: asset_valuation_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Usa otro puerto si ya hay uno expuesto
    volumes:
      - postgres_data_asset_valuation:/var/lib/postgresql/data
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend

  asset-valuation-service:
    build:
      context: .
    container_name: asset-valuation-service
    depends_on:
      - postgres_valuation
      - kafka
    env_file:
      - .env
    restart: on-failure
    networks:
      - backend

volumes:
  postgres_data_asset_valuation:

networks:
  backend:
